Cypress.Commands.add('gui_fillMandatoryFieldsAndSubmit', (idOfTheFieldName, idOfTheFieldLastName, idOfTheFieldEmail, idOfTheFieldFeedback, classOfTheSubmitButton, contentOfTheSubmitButton, classOfTheSuccessMessage, client) => {
    cy.get(idOfTheFieldName).should('be.visible')
    cy.get(idOfTheFieldName).type(client.firstName)
    cy.get(idOfTheFieldName).should('have.value', client.firstName)
    cy.get(idOfTheFieldLastName).should('be.visible')
    cy.get(idOfTheFieldLastName).type(client.lastName)
    cy.get(idOfTheFieldLastName).should('have.value', client.lastName)
    cy.get(idOfTheFieldEmail).should('be.visible')
    cy.get(idOfTheFieldEmail).type(client.email)
    cy.get(idOfTheFieldEmail).should('have.value', client.email)
    cy.get(idOfTheFieldFeedback).should('be.visible')
    cy.get(idOfTheFieldFeedback).type(client.feedback)
    cy.get(idOfTheFieldFeedback).should('have.value', client.feedback)
    cy.contains(classOfTheSubmitButton, contentOfTheSubmitButton).click()
    cy.get(classOfTheSuccessMessage).should('be.visible')
})